In [70]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [71]:
X = np.vstack([(np.random.rand(10, 2)*5),(np.random.rand(10, 2)*10)])
Y = np.hstack([[0]*10 , [1]*10])
df = pd.DataFrame(X,columns=["X1","X2"])
df["Y"] = Y
df

X1        X2  Y
0   2.920979  3.544249  0
1   0.742667  2.142254  0
2   3.469450  0.523099  0
3   2.198026  0.831011  0
4   2.534893  4.095179  0
5   0.450534  4.000344  0
6   2.825632  2.946739  0
7   0.990503  2.180591  0
8   1.479519  0.187788  0
9   0.153424  2.265525  0
10  7.448641  5.572954  1
11  3.851136  1.680728  1
12  8.382613  5.990518  1
13  7.827148  8.485092  1
14  6.031630  7.810606  1
15  6.157369  0.211652  1
16  7.504646  1.760421  1
17  4.585142  5.131227  1
18  4.840209  8.443858  1
19  1.748139  0.146349  1

In [72]:
# converting Target Variable to vector of number of classes
Z = np.zeros((20,2))
for i in range(20):
    Z[i, Y[i]] = 1

In [73]:
X.shape

(20, 2)

In [74]:
# initiating Random Weights and Bias
W1_1 = np.random.randn(3,2)
B1_1 = np.random.randn(3)
W1_2 = np.random.randn(3,2)
B1_2 = np.random.randn(2)


In [75]:
W1_1

array([[ 0.46088845,  0.66237401],
       [-2.29510333, -1.19592931],
       [-0.33310116, -0.79139077]])

In [76]:
B1_2

array([0.60319905, 1.00686114])

In [77]:
W1_2

array([[ 0.61229731,  1.10012937],
       [ 0.56435253, -0.71279944],
       [-0.26085948,  0.54842807]])

In [78]:
B1_2

array([0.60319905, 1.00686114])

In [79]:
W1_1.T

array([[ 0.46088845, -2.29510333, -0.33310116],
       [ 0.66237401, -1.19592931, -0.79139077]])

In [80]:
X.dot(W1_1.T)

array([[  3.69386407, -10.94262038,  -3.7778676 ],
       [  1.76125994,  -4.26648208,  -1.94274313],
       [  1.94551659,  -8.5883361 ,  -1.56965344],
       [  1.56348481,  -6.03852732,  -1.38981931],
       [  3.88084333, -10.71538668,  -4.08526297],
       [  2.85736951,  -5.81814968,  -3.31590842],
       [  3.25414409, -10.0092079 ,  -3.27324293],
       [  1.90087852,  -4.88114041,  -2.05563761],
       [  0.80627928,  -3.62023018,  -0.64144343],
       [  1.57133633,  -3.06153215,  -1.84402136],
       [  7.12437246, -23.76025934,  -6.89153531],
       [  2.88821464, -10.84878689,  -2.61293048],
       [  7.83141305, -26.40319951,  -7.53309884],
       [  9.22774652, -28.11168387,  -9.32225551],
       [  7.95345105, -23.1841464 ,  -8.19038452],
       [  2.97805288, -14.38491826,  -2.21852606],
       [  4.62486207, -19.32927773,  -3.89298753],
       [  5.51203049, -16.65995968,  -5.5881219 ],
       [  7.82378845, -21.20703678,  -8.29467046],
       [  0.90263466,  -4.18718

In [81]:
# forward propagation
def fop(X,W1_1,B1_1,W1_2,B1_2):
    M = 1 / (1 * np.exp(-(X.dot(W1_1.T) + B1_1)))
    A = M.dot(W1_2) + B1_2
    expA = np.exp(A)
    Y = expA / expA.sum(axis=1, keepdims=True)
    return Y, M

In [82]:
fop(X,W1_1,B1_1,W1_2,B1_2)

C:\Users\Akshit\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in exp
  """
C:\Users\Akshit\anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  


(array([[4.16688278e-12, 1.00000000e+00],
        [1.55421121e-02, 9.84457888e-01],
        [7.21618755e-03, 9.92783812e-01],
        [2.92345469e-02, 9.70765453e-01],
        [2.07369805e-14, 1.00000000e+00],
        [9.32702951e-06, 9.99990673e-01],
        [4.02587935e-08, 9.99999960e-01],
        [8.91737269e-03, 9.91082627e-01],
        [1.30406090e-01, 8.69593910e-01],
        [2.98958400e-02, 9.70104160e-01],
        [           nan,            nan],
        [6.52185852e-06, 9.99993478e-01],
        [           nan,            nan],
        [           nan,            nan],
        [           nan,            nan],
        [2.19581914e-06, 9.99997804e-01],
        [2.51095287e-29, 1.00000000e+00],
        [6.38430788e-70, 1.00000000e+00],
        [           nan,            nan],
        [1.14321155e-01, 8.85678845e-01]]),
 array([[5.28806165e+01, 1.05695820e-05, 4.13222698e-03],
        [7.65556410e+00, 8.38431985e-03, 2.58921790e-02],
        [9.20447128e+00, 1.11303926e-04, 3

In [83]:
# backpropagation
def diff_W1_2(H, Z, Y):
    return H.T.dot(Z - Y)

In [84]:
def diff_W1_1(X,H,Z,output, W1_2):
    dZ = (Z - output).dot(W1_2.T) * H * (1-H)
    return X.T.dot(dZ)

In [85]:
def diff_B2(Z, Y):
    return (Z - Y).sum(axis=0)

def diff_B1(Z, Y, W1_2, H):
    return ((Z - Y).dot(W1_2.T) * H * (1 - H)).sum(axis=0)

In [86]:
learning_rate = 1e-3
for epoc in range(5000):
    output, hidden = fop(X,W1_1,B1_1,W1_2,B1_2)
    W1_2 += learning_rate + diff_W1_2(hidden, Z, output)
    B1_2 += learning_rate + diff_B2(Z, output)
    W1_1 += learning_rate + diff_W1_1(X, hidden, Z, output, W1_2).T
    B1_2 += learning_rate + diff_B1(Z, output, W1_2, hidden)

C:\Users\Akshit\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in exp
  """
C:\Users\Akshit\anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  


ValueError: operands could not be broadcast together with shapes (2,) (3,) (2,) 